# Generated by Django 5.0.1 on 2024-02-11 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Seller', '0003_coupon_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2024, 2, 11)),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 2, 11)),
        ),
    ]
