# Generated by Django 5.0.1 on 2024-02-11 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Seller', '0005_alter_coupon_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 0, 1, 34, 585964)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 2, 12)),
        ),
    ]
