# Generated by Django 5.0.1 on 2024-02-11 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Seller', '0006_alter_coupon_expiry_date_alter_coupon_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 0, 2, 3, 152783)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
