# Generated by Django 5.0.1 on 2024-02-11 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Seller', '0007_coupon_date_alter_coupon_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='date',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 0, 3, 4, 433861)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 0, 3, 4, 433861)),
        ),
    ]
