# Generated by Django 5.0.1 on 2024-02-13 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Seller', '0013_alter_coupon_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='minPurches',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 16, 9, 6, 194028)),
        ),
    ]
