# Generated by Django 5.0.1 on 2024-02-13 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Seller', '0015_alter_coupon_start_date_user_used_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 22, 45, 47, 637950)),
        ),
        migrations.DeleteModel(
            name='User_used_coupon',
        ),
    ]
