# Generated by Django 5.0.1 on 2024-02-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0004_alter_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
