# Generated by Django 5.0.1 on 2024-02-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0006_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='created_by',
        ),
    ]
