# Generated by Django 5.0.1 on 2024-02-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0008_alter_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
