# Generated by Django 5.0.1 on 2024-02-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0003_delete_order_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.CharField(default='', max_length=100),
        ),
    ]
