# Generated by Django 5.0.1 on 2024-02-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Order', '0004_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
