# Generated by Django 5.0.1 on 2024-02-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0002_user_role_sellerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sellerProfile',
        ),
    ]
